name: Deploy Shopify Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest

      - name: Authenticate with Shopify
        run: shopify theme push --store https://kpw1fv-su.myshopify.com --password=${{ secrets.SHOPIFY_PASSWORD }}
